apiVersion: v1
description: Fermilab Helm chart for a ES exporter CronJob
home: https://github.com/bjwhite-fnal/rucio-fnal
maintainers:
- email: bjwhite@fnal.gov 
  name: Brandon White 
name: rucio-es-cron
version: 1.0
appVersion:  1.0
sources:
    - https://github.com/bjwhite-fnal/rucio-fnal
