apiVersion: v1
kind: Pod
metadata:
  name: rucio-db-upgrade
spec:
  serviceAccountName: useroot
  containers:
  - name: rucio-db-upgrade
    image: rucio/rucio-init:release-33.0.0
    command: ["sleep"]
    args: ["infinity"]
    env:
    - name: RUCIO_CFG_DATABASE_DEFAULT
      valueFrom:
        secretKeyRef:
          name: fnal-db-connstr-dkcfbffc94
          key: db-connstr.txt
