---
# Source: rucio-webui/templates/deployment.yaml
apiVersion: v1
kind: Secret
metadata:
  name: fnal-rucio-webui.config.yaml
  labels:
    app: rucio-webui
    chart: rucio-webui-34.0.3
    release: "fnal"
    heritage: "Helm"
type: Opaque
data:
  common.json: "ewogICJib290c3RyYXAiOiB7CiAgICAieDUwOV9lbWFpbCI6ICJiandoaXRlQGZuYWwuZ292IiwKICAgICJ4NTA5X2lkZW50aXR5IjogIi9EQz1vcmcvREM9Y2lsb2dvbi9DPVVTL089RmVybWkgTmF0aW9uYWwgQWNjZWxlcmF0b3IgTGFib3JhdG9yeS9PVT1QZW9wbGUvQ049QnJhbmRvbiBXaGl0ZS9DTj1VSUQ6Ymp3aGl0ZSIKICB9LAogICJjb3JlIjogewogICAgInVzZV90ZW1wX3RhYmxlcyI6ICJUcnVlIgogIH0sCiAgImh0dHBkIjogewogICAgImtlZXBfYWxpdmUiOiAiT24iLAogICAgImtlZXBfYWxpdmVfdGltZW91dCI6ICI1IiwKICAgICJtYXhfY2xpZW50cyI6ICIyMCIsCiAgICAibWF4X2Nvbm5lY3Rpb25zX3Blcl9jaGlsZCI6ICIyMDQ4IiwKICAgICJtYXhfa2VlcF9hbGl2ZV9yZXF1ZXN0cyI6ICIxMjgiLAogICAgIm1heF9yZXF1ZXN0X3dvcmtlcnMiOiAiMTI4MCIsCiAgICAibWF4X3JlcXVlc3RzX3Blcl9jaGlsZCI6ICI4MTkyIiwKICAgICJtYXhfc3BhcmVfc2VydmVycyI6ICI1IiwKICAgICJtYXhfc3BhcmVfdGhyZWFkcyI6ICIyMCIsCiAgICAibWluX3NwYXJlX3NlcnZlcnMiOiAiMSIsCiAgICAibWluX3NwYXJlX3RocmVhZHMiOiAiMSIsCiAgICAibXBtX21vZGUiOiAiZXZlbnQiLAogICAgInNlcnZlcl9saW1pdCI6ICIxMCIsCiAgICAic3RhcnRfc2VydmVycyI6ICIxIiwKICAgICJ0aHJlYWRzX2xpbWl0IjogIjEyOCIsCiAgICAidGhyZWFkc19wZXJfY2hpbGQiOiAiNSIsCiAgICAidGltZW91dCI6IDMwMAogIH0sCiAgImxvZ3MiOiB7CiAgICAiZXhwb3NlSHR0cGRMb2dzIjogdHJ1ZSwKICAgICJleHBvc2VXZWJ1aUxvZ3MiOiB0cnVlCiAgfSwKICAib2lkY19wcm92aWRlcnMiOiB7CiAgICAiY2VybiI6IHsKICAgICAgImF1dGhvcml6YXRpb25fdXJsIjogIiIsCiAgICAgICJjbGllbnRfaWQiOiAiIiwKICAgICAgImNsaWVudF9zZWNyZXQiOiAiIiwKICAgICAgInJlZGlyZWN0X3VybCI6ICIiLAogICAgICAicmVmcmVzaF90b2tlbl91cmwiOiAiIiwKICAgICAgInRva2VuX3VybCI6ICIiLAogICAgICAidXNlcmluZm9fdXJsIjogIiIKICAgIH0KICB9LAogICJwb2xpY3kiOiB7CiAgICAicGFja2FnZSI6ICJmZXJtaWxhYiIKICB9LAogICJ2byI6IHsKICAgICJkZWYiOiB7CiAgICAgICJuYW1lIjogImRlZmF1bHQiLAogICAgICAib2lkY19lbmFibGVkIjogIkZhbHNlIiwKICAgICAgIm9pZGNfcHJvdmlkZXJzIjogIiIKICAgIH0KICB9LAogICJ3ZWJ1aSI6IHsKICAgICJob3N0bmFtZSI6ICJodHRwczovL3dlYnVpLWludC1ydWNpby5mbmFsLmdvdiIsCiAgICAibXVsdGl2b19lbmFibGVkIjogIkZhbHNlIiwKICAgICJvaWRjX2VuYWJsZWQiOiAiRmFsc2UiLAogICAgIm9pZGNfcHJvdmlkZXJzIjogIiIsCiAgICAicHJvamVjdF91cmwiOiAiaHR0cHM6Ly9naXRodWIuY29tL2Jqd2hpdGUtZm5hbC9ydWNpby1hbXMiLAogICAgInJ1Y2lvX2F1dGhfaG9zdCI6ICJodHRwczovL2ludC1ydWNpby5mbmFsLmdvdiIsCiAgICAicnVjaW9faG9zdCI6ICJodHRwczovL2ludC1ydWNpby5mbmFsLmdvdiIsCiAgICAidXNlcmNlcnQiOiAiL29wdC9ydWNpby9ldGMvdXNlcmNlcnRfd2l0aF9rZXkucGVtIiwKICAgICJ2b19kZWZhdWx0IjogImRlZiIsCiAgICAidm9fbGlzdCI6ICJkZWYiCiAgfQp9"
---
# Source: rucio-webui/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fnal-rucio-webui
  labels:
    app: rucio-webui
    chart: rucio-webui-34.0.3
    release: fnal
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: http
  selector:
    app: rucio-webui
    release: fnal
---
# Source: rucio-webui/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fnal-rucio-webui
  labels:
    app: rucio-webui
    chart: rucio-webui-34.0.3
    release: fnal
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rucio-webui
      release: fnal
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: rucio-webui
        release: fnal
      annotations:
        checksum/config: 16aba41356f7a4a0520f16919cac596d7ce74482
    spec:
      volumes:
      - name: config
        secret:
          secretName: fnal-rucio-webui.config.yaml
      - name: httpdlog
        emptyDir: {}
      - name: webui-log
        emptyDir: {}
      - name: hostcert
        secret:
          secretName: fnal-hostcert
      - name: hostkey
        secret:
          secretName: fnal-hostkey
      - name: cafile
        secret:
          secretName: fnal-cafile
      containers:
        - name: httpd-error-log
          image: busybox
          args: [/bin/sh, -c, 'tail -n+1 -F /var/log/httpd/error_log']
          volumeMounts:
          - name: httpdlog
            mountPath: /var/log/httpd
        - name: webui-log
          image: busybox
          args: [/bin/sh, -c, 'tail -n+1 -F /var/log/webui/rucio-webui-out.log /var/log/webui/rucio-webui-error.log']
          volumeMounts:
          - name: webui-log
            mountPath: /var/log/webui/
        - name: rucio-webui
          image: "rucio/rucio-ui:release-35.4.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: httpdlog
              mountPath: /var/log/httpd
            - name: webui-log
              mountPath: /root/.pm2/logs/
            - name: hostcert
              mountPath: /opt/certs/hostcert.pem
              subPath: hostcert.pem
            - name: hostkey
              mountPath: /opt/certs/hostkey.pem
              subPath: hostkey.pem
            - name: cafile
              mountPath: /opt/certs/ca.pem
              subPath: ca.pem
          env:
            - name: RUCIO_HTTPD_KEEP_ALIVE
              value: "On"
            - name: RUCIO_HTTPD_KEEP_ALIVE_TIMEOUT
              value: "5"
            - name: RUCIO_HTTPD_MAX_CLIENTS
              value: "20"
            - name: RUCIO_HTTPD_MAX_CONNECTIONS_PER_CHILD
              value: "2048"
            - name: RUCIO_HTTPD_MAX_KEEP_ALIVE_REQUESTS
              value: "128"
            - name: RUCIO_HTTPD_MAX_REQUEST_WORKERS
              value: "1280"
            - name: RUCIO_HTTPD_MAX_REQUESTS_PER_CHILD
              value: "8192"
            - name: RUCIO_HTTPD_MAX_SPARE_SERVERS
              value: "5"
            - name: RUCIO_HTTPD_MAX_SPARE_THREADS
              value: "20"
            - name: RUCIO_HTTPD_MIN_SPARE_SERVERS
              value: "1"
            - name: RUCIO_HTTPD_MIN_SPARE_THREADS
              value: "1"
            - name: RUCIO_HTTPD_MPM_MODE
              value: "event"
            - name: RUCIO_HTTPD_SERVER_LIMIT
              value: "10"
            - name: RUCIO_HTTPD_START_SERVERS
              value: "1"
            - name: RUCIO_HTTPD_THREADS_LIMIT
              value: "128"
            - name: RUCIO_HTTPD_THREADS_PER_CHILD
              value: "5"
            - name: RUCIO_HTTPD_TIMEOUT
              value: "300"
            - name: RUCIO_WEBUI_HOSTNAME
              value: "https://webui-int-rucio.fnal.gov"
            - name: RUCIO_WEBUI_MULTIVO_ENABLED
              value: "False"
            - name: RUCIO_WEBUI_OIDC_ENABLED
              value: "False"
            - name: RUCIO_WEBUI_OIDC_PROVIDERS
              value: ""
            - name: RUCIO_WEBUI_PROJECT_URL
              value: "https://github.com/bjwhite-fnal/rucio-ams"
            - name: RUCIO_WEBUI_RUCIO_AUTH_HOST
              value: "https://int-rucio.fnal.gov"
            - name: RUCIO_WEBUI_RUCIO_HOST
              value: "https://int-rucio.fnal.gov"
            - name: RUCIO_WEBUI_USERCERT
              value: "/opt/rucio/etc/usercert_with_key.pem"
            - name: RUCIO_WEBUI_VO_DEFAULT
              value: "def"
            - name: RUCIO_WEBUI_VO_LIST
              value: "def"
            
            - name: RUCIO_WEBUI_OIDC_PROVIDER_CERN_AUTHORIZATION_URL
              value: ""
            - name: RUCIO_WEBUI_OIDC_PROVIDER_CERN_CLIENT_ID
              value: ""
            - name: RUCIO_WEBUI_OIDC_PROVIDER_CERN_CLIENT_SECRET
              value: ""
            - name: RUCIO_WEBUI_OIDC_PROVIDER_CERN_REDIRECT_URL
              value: ""
            - name: RUCIO_WEBUI_OIDC_PROVIDER_CERN_REFRESH_TOKEN_URL
              value: ""
            - name: RUCIO_WEBUI_OIDC_PROVIDER_CERN_TOKEN_URL
              value: ""
            - name: RUCIO_WEBUI_OIDC_PROVIDER_CERN_USERINFO_URL
              value: ""
            
            - name: RUCIO_WEBUI_VO_DEF_NAME
              value: "default"
            - name: RUCIO_WEBUI_VO_DEF_OIDC_ENABLED
              value: "False"
            - name: RUCIO_WEBUI_VO_DEF_OIDC_PROVIDERS
              value: ""
            - name: RUCIO_WEBUI_RUCIO_HOST
              value: https://int-rucio.fnal.gov
            - name: RUCIO_WEBUI_RUCIO_AUTH_HOST
              value: https://int-rucio.fnal.gov
            - name: RUCIO_LOG_LEVEL
              value: "INFO"
            - name: RUCIO_ENABLE_LOGS
              value: "True"
            - name: RUCIO_LOG_FORMAT
              value: '[%{%Y-%m-%d %H:%M:%S}t]\t%v\t%h\t%{X-Forwarded-For}i\t%{X-Rucio-RequestId}i\t%>s\t%I\t%B\t%D\t\"%r\"\t\"%{X-Rucio-Auth-Token}i\"\t\"%{User-Agent}i\"\t%{X-Rucio-Script}i'
            - name: RUCIO_WEBUI_ENABLE_SSL
              value: "True"
          resources:
            {}
