apiVersion: batch/v1
kind: CronJob
metadata:
  name: fnal-sync-ferry-users
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: useroot
          initContainers:
          - name: grid-certs
            image: docker.io/bjwhitefnal/grid-security-files:32
            command: ["/bin/bash", "-c", "chmod 755 /out/ && cp -rv --preserve=links /grid-certificates/* /out/"]
            volumeMounts:
            - name: ca-volume
              mountPath: /out/
          volumes:
          - name: rucio-config
            secret:
              secretName: fnal-ferry-rucio-config
          - name: proxy-volume
            secret:
              secretName: fnal-rucio-x509up
          containers:
            - name: sync-ferry-users
              image: "imageregistry.fnal.gov/rucio-ams/rucio-client:34.1.0.fnal"
              imagePullPolicy: Always
              command:
              - /bin/bash
              - python3
              - /scripts/sync_ferry_users.py
              resources:
                limits:
                  cpu: 500m
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
              volumeMounts:
                - name: rucio-config
                  mountPath: /opt/rucio/etc
                - name: proxy-volume
                  mountPath: /opt/proxy
              env:
                - name: RUCIO_URL
                  value: ""
                - name: FERRY_VO
                  value: "dune"
                - name: FERRY_URL
                  value: "https://ferry.fnal.gov:8445"
          restartPolicy: OnFailure
