apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-logrotate
spec:
  schedule: "4 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.serviceAccountName }}
          volumes:
          - name: ssl-credentials
            secret:
              secretName: ssl-secrets
          - name: rucio-logs
            persistentVolumeClaim:
              claimName: "pv-rucio-{{ .Values.experiment }}-logs"
          containers:
            - name: {{ .Release.Name }}-logrotate 
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              volumeMounts:
              - name: ssl-credentials
                mountPath: /opt/ssl
                readOnly: true
              - name: rucio-logs
                mountPath: /rucio/logs
              env:
                {{- range $key1, $val1 := .Values.optional_config }}
                - name: {{ $key1 | upper }}
                  value: "{{ $val1  }}"
                {{- end}}
          restartPolicy: OnFailure
