apiVersion: v1
kind: Route
metadata:
  name: {{ .Values.messengerRoute.serviceName  }}-route
  labels:
    app: {{ .Values.messengerRoute.app }} 
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  host: {{ .Values.messengerRoute.host }} 
  to:
    kind: Service
    name: rucio-messenger
  tls:
    termination: passthrough
