FROM docker.io/library/golang:1.20 AS devbuild
WORKDIR godir/
COPY ./go.mod ./
COPY ./ferry-sync-cron.go ./
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o /ferry-sync-cron.exe
WORKDIR /
ENTRYPOINT ["/ferry-sync-cron.exe"]

FROM docker.io/library/golang:1.20 AS prodbuild
WORKDIR /
COPY --from=devbuild /ferry-sync-cron.exe /ferry-sync-cron.exe
ENTRYPOINT ["/ferry-sync-cron.exe"]
