apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rucio
resources:
  - rucio-server-helm.yaml
configMapGenerator:
  - name: rucio-ams-server
    files:
      - values.yaml=rucio-ams-server.yaml
configurations:
  - kustomizeconfig.yaml
