apiVersion: v1
kind: Service
metadata:
  name: {{ template "rucio.fullname" . }}
  labels:
    app: {{ template "rucio.name" . }}
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.externalIP }}
  externalIPs:
    - {{ .Values.service.externalIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
  selector:
    app: {{ template "rucio.name" . }}
    release: {{ .Release.Name }}
