apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
resources:
#  - namespace.yaml
  - release.yaml
configMapGenerator:
  - name: mappings
    files:
      - values.yaml=statsd-prometheus-mapping.yaml
configurations:
  - kustomizeconfig.yaml
