apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: statsd-exporter
spec:
  releaseName: statsd-exporter
  chart:
    spec:
      chart: rucio-statsd-exporter
      version: "1.1.1"
      sourceRef:
        kind: HelmRepository
        name: cms-kubernetes
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: mappings
    - kind: ConfigMap
      name: instance-settings
