apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
configMapGenerator:
  - name: instance-settings
    files:
      - values.yaml=int-statsd-exporter.yaml
configurations:
  - kustomizeconfig.yaml
