apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: rucio-git
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/ericvaandering/helm-charts.git
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/helm/
