apiVersion: v1
description: Fermilab Helm Chart runs logrotate cronjob for cleaning up the persistent volume where logs are stored
home: https://github.com/bjwhite-fnal/rucio-fnal
maintainers:
- email: bjwhite@fnal.gov 
  name: Brandon White 
name: rucio-logrotate 
version: 1.0 
appVersion: 1.0 
sources:
