# Rucio Web UI container configuration options
# This is a YAML-formatted file
# Declare variables to be passed into your templates.

serviceAccountName: useroot

rucio_ca_path: /etc/grid-security/certificates
webui_certkeycombined_path: /etc/grid-security/hostcertkeycombined.pem

image:
  repository: bjwhitefnal/fnal-rucio-webui
  tag: latest
  pullPolicy: Always

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

minReadySeconds: 5

exposeErrorLogs: 0

ingress:
  enabled: 0

webuiRoute:
  app: rucio-webui
  host: webui-int-rucio.okd.fnal.gov
  serviceName: rucio-int-rucio-ui

service:
  type: ClusterIP
  port: 443 
  targetPort: 443
  tls:
    enabled: true

monitor:
  carbon_server: "lsdataitb.fnal.gov"
  carbon_port: 8225
  user_scope: "rucio.int_okd_dev"

logging:
  log_level: 0

persistentVolumes:
  rucio-logs:
    name: "pv-rucio-int-logs"
    mountPath: /rucio/logs

httpd_config:
  log_dir: "/rucio/logs"

optional_config:
  experiment: Uses $EXPERIMENT 
  policy_pkg_dir: /opt/rucio/permissions
  rucio_enable_logfile: "True"
