# Add initContainers to Deployments requring OSG CA certificates installed
# This will result in an initContainer being created before the Rucio daemon container
# This initContainer uses an image that has the most recent CA certs baked in
# Baked in certs are copied to a mounted volume. The initContainer concludes actions.
# Volume that initContainer copied CA certificates into is mounted by the Rucio daemon.
# You've got certs.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fnal-automatix
spec:
  template:
    spec:
      initContainers:
      - name: grid-certs
        image: docker.io/bjwhitefnal/grid-security-files:32
        command: ["/bin/bash", "-c", "chmod 755 /out/ && cp -rv --preserve=links /grid-certificates/* /out/ && cp -rv --preserve=links /grid-certificates/* /out2/"]
        volumeMounts:
        - name: ca-volume
          mountPath: /out/
        - name: ca-volume-reaper
          mountPath: /out2/
      volumes:
       - name: ca-volume
         secret:
           $patch: delete
         emptyDir: {}
       - name: ca-volume-reaper
         secret:
           $patch: delete
         emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fnal-reaper
spec:
  template:
    spec:
      initContainers:
      - name: grid-certs
        image: docker.io/bjwhitefnal/grid-security-files:32
        command: ["/bin/bash", "-c", "chmod 755 /out/ && cp -rv --preserve=links /grid-certificates/* /out/"]
        imagePullPolicy: Always
        volumeMounts:
        - name: ca-volume
          mountPath: /out/
      volumes:
       - name: ca-volume
         secret:
           $patch: delete
         emptyDir: {}
---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: fnal-rucio-ui
#spec:
#  template:
#    spec:
#      initContainers:
#      - name: grid-certs
#        image: docker.io/bjwhitefnal/grid-security-files:32
#        command: ["/bin/bash", "-c", "chmod 755 /out/ && cp -rv --preserve=links /grid-certificates/* /out/"]
#        volumeMounts:
#        - name: ca-volume
#          mountPath: /out/
#      volumes:
#       - name: ca-volume
#         secret:
#           $patch: delete
#         emptyDir: {}
