apiVersion: batch/v1
kind: CronJob
metadata:
  name: fnal-renew-fts-proxy
spec:
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: useroot
---
apiVersion: batch/v1
kind: Job
metadata:
    name: fnal-renew-fts-proxy-on-helm-install
spec:
  template:
    spec:
      restartPolicy: OnFailure
