# Default values for rucio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceAccountName: useroot

useSSL: true

## replicaCount gives the number of server pods to run
replicaCount: 1

# When set, run extra busybox containers in the relevant pods to also expose the error logs
exposeErrorLogs: 0

service:
  # type: NodePort
  # # Run the webui server on port 443 instead of 80 and accept X509 certificates and proxies
  # useSSL: true
  # port: 443
  # targetPort: https
  # portName: https
  type: ClusterIP
  port: 443
  targetPort: 443
  name: https
  tls:
    enabled: true
  allocateLoadBalancerNodePorts: false

image:
  repository: imageregistry.fnal.gov/docker.io/rucio/rucio-webui
  tag: release-35.4.0
  pullPolicy: Always

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

minReadySeconds: 5

ingress:
  enabled: 0

additionalSecrets:
  - secretName: ca-volume
    mountPath: /etc/grid-security/certificates
# - volumeName: gcssecret
#   secretName: gcssecret
#   mountPath: /opt/rucio/etc/gcs_rucio.json
#   subPath: gcs_rucio.json

## values used to configure apache
httpd_config:
  legacy_dn: "True"
  log_dir: "/rucio/logs"
  # mpm_mode: "event"
  # start_servers: "1"
  # min_spare_threads: "1"
  # max_spare_threads: "20"
  # threads_per_child: "5"
  # max_clients: "20"
  # max_requests_per_child: "8192"
  tls:
    enabled: true

## values used to configure Rucio
config:
  bootstrap:
    x509_identity: "/DC=org/DC=cilogon/C=US/O=Fermi National Accelerator Laboratory/OU=People/CN=Brandon White/CN=UID:bjwhite"
    x509_email: "bjwhite@fnal.gov"

  policy:
    package: fermilab

  # common:
    ## config.common.logdir: the default directoy to write logs to (default: "/var/log/rucio")
    # logdir: "/var/log/rucio"
    ## config.common.logdir: the max loglevel (default: "DEBUG")
    # loglevel: "DEBUG"
    ## config.common.mailtemplatedir: directory containing the mail templates (default: "/opt/rucio/etc/mail_templates")
    # mailtemplatedir: "/opt/rucio/etc/mail_templates"

  ## Only necessary for webui deployments
  webui:
    rucio_host: "https://icarus-rucio.fnal.gov"
    rucio_auth_host: "https://icarus-rucio.fnal.gov"
    hostname: "webui-icarus-rucio.fnal.gov"
    project_url: "https://fnal.gov"
    oidc_enabled: "False"
    enable_ssl: "True"
    server_ca_bundle: "/etc/grid-security/ca.pem"

optional_config:
  pythonpath: /opt/rucio/permissions
  #POLICY_PKG_DIR: /opt/rucio/permissions

additionalEnvs:
  - name: RUCIO_CA_PATH
    value: "/etc/grid-security/certificates"
  - name: RUCIO_ENABLE_SSL
    value: "True"
  - name: RUCIO_HTTPD_LEGACY_DN
    value: "True"
  - name: RUCIO_LOG_LEVEL
    value: debug

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
secretMounts:
  # Custom to install metacat? Needed for webui?
  #- secretName: docker-entrypoint-webui
  #  mountPath: /docker-entrypoint.sh
  #  subPath: docker-entrypoint.sh
  #  defaultMode: 0750
  - secretName: hostcert
    mountPath: /etc/grid-security/hostcert.pem
    subPath: hostcert.pem
  - secretName: hostkey
    mountPath: /etc/grid-security/hostkey.pem
    subPath: hostkey.pem
  - secretName: cafile
    mountPath: /etc/grid-security/ca.pem
    subPath: ca.pem
  - secretName: ca-volume
    mountPath: /etc/grid-security/certificates
  - secretName: httpd-custom-config
    mountPath: /etc/httpd/conf.d/fnal-custom-config.conf
    subPath: fnal-custom-config.conf

nodeSelector: {}

tolerations: []

affinity: {}
