# Configure Filebeat to read the logs written to the shared PVC claim
filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /rucio/logs/*log*

# Logging config
logging.level: info
logging.to_stderr: true
#logging.to_files: true
#logging.files:
#    path: /rucio/logs
#    name: filebeat
#    keepfiles: 3

# Ship the events to Logstash for processing/cleaning
output.logstash:
    enabled: true
    hosts: ["rucio-logstash:5044"]
