# Configure Filebeat to read the logs written to the shared PVC claim
filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /rucio/logs/*.log

# Drop the log fields containing auth token information
#processors:
#  - drop_fields:
#      fields: ["cpu.user", "cpu.system"]

# Ship the log file contents to the Distributed Computing Support Kafka instance
output.kafka:
    enabled: true
    # Kafka brokers run by Distributed Computing Support
    hosts: ["lssrv03:9092", "lssrv04:9092", "lssrv05:9092"]

    # message topic selection + partitioning
    topic: 'ingest.logs.rucio.dune'
    partition.round_robin:
      reachable_only: false

    required_acks: 1
    compression: gzip
    max_message_bytes: 1000000
