---
# Source: rucio-messenger/templates/messenger_service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fnal-rucio-messenger
  labels:
    app: rucio-messenger
    chart: rucio-messenger-0.3.0
    release: rucio-hypot-messenger
    heritage: Helm
spec:
  type: ClusterIP 
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    app: rucio-messenger
    release: rucio-hypot-messenger
---
# Source: rucio-messenger/templates/messenger_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fnal-rucio-messenger
  labels:
    app: rucio-messenger
    chart: rucio-messenger-0.3.0
    release: rucio-hypot-messenger
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fnal-rucio-messenger
      release: rucio-hypot-messenger
  minReadySeconds: 
  template:
    metadata:
      labels:
        app: fnal-rucio-messenger
        release: rucio-hypot-messenger
    spec:
      serviceAccountName: useroot
      volumes:
        - name: ssl-credentials
          secret:
            secretName: ssl-secrets
        - name: rabbitmq-conf
          secret:
            secretName: fnal-rabbitmq-conf
        - name: enabled-plugins
          secret: 
            secretName: fnal-rabbitmq-enabled-plugins
      containers:
        - name: rucio-messenger
          image: "imageregistry.fnal.gov/rucio-ams/rucio-ams-messenger:1.29.12"
          imagePullPolicy: Always
          volumeMounts:
            - name: ssl-credentials
              mountPath: /etc/rabbitmq/ssl
              readOnly: true
            - name: rabbitmq-conf
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
            - name: enabled-plugins
              mountPath: /etc/rabbitmq/enabled_plugins
              subPath: enabled_plugins
          env:
            - name: EXPERIMENT
              value: "hypot"
            - name: RUCIO_MESSENGER_SERVICE_PORT_HTTPS
              value: "443"
