---
# Source: rucio-prometheus/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rucio-hypot-prometheus
  labels:
    app: rucio-prometheus
    chart: rucio-prometheus-1
    release: rucio-hypot-prometheus
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rucio-prometheus
      release: rucio-hypot-prometheus
  minReadySeconds: 
  template:
    metadata:
      labels:
        app: rucio-prometheus
        release: rucio-hypot-prometheus
    spec:
      serviceAccountName: useroot
      containers:
        - name: rucio-prometheus
          image: "imageregistry.fnal.gov/rucio-ams/rucio-ams-prometheus:32"
          imagePullPolicy: Always
          env:
            - name: EXPERIMENT
              value: "hypot"
            - name: LANDSCAPE_REMOTE_WRITE_ENDPOINT
              value: "http://lsdataitb.fnal.gov:9009/api/v1/push"
