{{- if gt .Values.logstashCount 0.0 -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "rucio.name" . }}
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.logstashCount }}
  selector:
    matchLabels:
      app: {{ template "rucio.name" . }}
      release: {{ .Release.Name }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ template "rucio.name" . }}
        release: {{ .Release.Name }}
    spec:
    {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
    {{- end }}
      volumes:
        - name: ssl-credentials
          secret:
            secretName: ssl-secrets
        - name: rucio-logs
          persistentVolumeClaim:
            claimName: "pv-rucio-{{ .Values.experiment }}-logs"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: ssl-credentials
              mountPath: /opt/ssl
              readOnly: true
            - name: rucio-logs
              mountPath: /rucio/logs
          env:
            - name: EXPERIMENT
              value: "{{ .Values.experiment }}"
{{ end }}
