# OSG Authentication Container configuration options
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceAccountName: useroot

experiment: dune

image:
  repository: bjwhitefnal/osg_authentication
  tag: latest
  pullPolicy: Always

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

minReadySeconds: 5

service:
  type: ClusterIP
  port: 80
  targetPort: 80
