{{- if gt .Values.messengerServerCount 0.0 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "rucio.name" . }}
  labels:
    app: {{ template "rucio.name" . }}
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP 
  ports:
    - port: {{ .Values.service.ssl_port }}
      targetPort: {{ .Values.service.ssl_targetPort }}
      protocol: TCP
      name: https
  selector:
    app: {{ template "rucio.name" . }}
    release: {{ .Release.Name }}
{{ end }}
