# my global config
global:
  scrape_interval: 60s
  evaluation_interval: 60s
  # scrape_timeout is set to the global default (10s).

  #external_labels:
  #  monitor: codelab
  #  foo: bar

#rule_files:
  #  - "first.rules"
  #  - "my/*.rules"

remote_write:
  - url: "REPLACE_WITH_LANDSCAPE_ENDPOINT"
#    name: drop_expensive
#    write_relabel_configs:
#      - source_labels: [__name__]
#        regex: expensive.*
#        action: drop
#    oauth2:
#      client_id: "123"
#      client_secret: "456"
#      token_url: "http://remote1/auth"
#      tls_config:
#        cert_file: valid_cert_file
#        key_file: valid_key_file
#
#  - url: http://remote2/push
#    name: rw_tls
#    tls_config:
#      cert_file: valid_cert_file
#      key_file: valid_key_file
#    headers:
#      name: value

scrape_configs:
  - job_name: prometheus
    honor_labels: true
    #enable_http2: false
    static_configs:
      - targets: ["localhost:9090"]
    # scrape_interval is defined by the configured global (15s).
    # scrape_timeout is defined by the global default (10s).

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

  - job_name: rucio-server
    honor_labels: true
    #enable_http2: false

    kubernetes_sd_configs:
      - role: pod 
        namespaces:
          names:
            - "rucio-REPLACE_WITH_EXPERIMENT"
        #api_server: "https://okddev-mgr.fnal.gov:6443"
        #enable_http2: false
        selectors:
        - role: "pod"
          label: "app=rucio-server"
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__address__]
        action: replace
        regex: ([^:]+):.*
        replacement: $1:8080
        target_label: __address__

  - job_name: rucio-server-auth
    honor_labels: true
    #enable_http2: false

    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - "rucio-REPLACE_WITH_EXPERIMENT"
        #api_server: "https://okddev-mgr.fnal.gov:6443"
        #enable_http2: false
        selectors:
        - role: "pod"
          label: "app=rucio-server-auth"
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__address__]
        action: replace
        regex: ([^:]+):.*
        replacement: $1:8080
        target_label: __address__

  - job_name: rucio-daemons
    honor_labels: true
    #enable_http2: false

    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - "rucio-REPLACE_WITH_EXPERIMENT"
        #api_server: "https://okddev-mgr.fnal.gov:6443"
        #enable_http2: false
        selectors:
        - role: "pod"
          label: "app-group=rucio-daemons"
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_name]
        action: drop
        regex: .+abacus.+
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__address__]
        action: replace
        regex: ([^:]+):.*
        replacement: $1:8080
        target_label: __address__

#    tls_config:
#      min_version: TLS12
#      ca_file: ca.pem
#      cert_file: hostcert.pem
#      key_file: hostcert.pem

#  - job_name: httpsd
#    http_sd_configs:
#      - url: "http://example.com/prometheus"
