global:
  scrape_interval: 60s
  evaluation_interval: 60s

remote_write:
  - url: "REPLACE_WITH_LANDSCAPE_ENDPOINT"
    write_relabel_configs:
      - target_label: "rucio_deployment"
        replacement: rucio-REPLACE_WITH_EXPERIMENT

scrape_configs:

  - job_name: rucio-daemons
    honor_labels: true

    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - "rucio-REPLACE_WITH_EXPERIMENT"
        selectors:
        - role: "pod"
          label: "app-group=rucio-daemons"
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_name]
        action: drop
        regex: .+abacus.+
      #- action: labelmap
      #  regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__address__]
        action: replace
        regex: ([^:]+):.*
        replacement: $1:8080
        target_label: __address__