apiVersion: v1
description: Fermilab Helm chart for a Prometheus server for remote_write to Landscape
home: https://github.com/bjwhite-fnal/rucio-ams
maintainers:
- email: bjwhite@fnal.gov 
  name: Brandon White 
name: rucio-prometheus 
version: 1.0
appVersion:  1.0
sources:
  - https://prometheus.io
