# Default values for rucio.
# This is a YAML-formatted file.
# Declare configuration parametersto be used when generating 
# OKD deployment YAML configs via Helm templates.

experiment: Uses $EXPERIMENT

# Number of pods to run for each daemon
abacusAccountCount: 1
abacusRseCount: 1
conveyorTransferSubmitterCount: 1
conveyorPollerCount: 1
conveyorFinisherCount: 1
hermesCount: 1
judgeCleanerCount: 1
judgeEvaluatorCount: 1
judgeInjectorCount: 1
judgeRepairerCount: 1
undertakerCount: 1
reaperCount: 1 
transmogrifierCount: 1
minosCount: 1
necromancerCount: 1

# Service Account
serviceAccountName: useroot

# Daemon Image
image:
  repository: bjwhitefnal/fnal-rucio-daemons
  tag: latest
  pullPolicy: Always

# Pod Upgrade Strategy
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

minReadySeconds: 5

# Daemons Specific Configuration Parameters
abacusAccount:
  threads: 1

abacusRse:
  threads: 1

conveyorTransferSubmitter:
  threads: 1
  activities: "'User Subscriptions' 'Recovery'"
  sleepTime: 10

conveyorPoller:
  threads: 1
  activities: "'User Subscriptions' 'Recovery'"

conveyorFinisher:
  threads: 1
  activities: "'User Subscriptions' 'Recovery'"

hermes:
  username: ____
  password: ____
  threads: 2 
  bulk: 100
  delay: 10
  port: 63614
  use_ssl: True
  destination: /topic/rucio.events.int
  voname: int
  email_from: int Rucio <bjwhite@fnal.gov>
  email_test: bjwhite@fnal.gov

judgeCleaner:
  threads: 1

judgeEvaluator:
  threads: 1

judgeInjector:
  threads: 1

judgeRepairer:
  threads: 1

undertaker:
  threads: 1

reaper:
  scheme: "gsiftp"
  threads: 1

minos:
  threads: 1

necromancer:
  threads: 1

ftsRenewal:
  enabled: 0
  image:
    repository: rucio/fts-cron
    tag: latest
    pullPolicy: Always
  voms: "fermilab:/fermilab/Role=Production"
  servers: "https://fts3-public.cern.ch:8446"

monitor:
  carbon_server: "lsdataitb.fnal.gov"
  carbon_port: 8225
  user_scope: "rucio.int_okd"

logging:
    # Set to 1 to turn on database queries in the logging output
    log_level: 0

## common config values used to configure the Rucio daemons
config:

  conveyor:
    max_time_in_queue: "User Subscriptions:5"
    #ftshosts: "https://fts3-public.cern.ch:8446"
    ftshosts: "https://fts3-dev.fnal.gov:8446"
    cacert: "/etc/grid-security/ca.pem"
    usercert: "/tmp/fts_proxy.pem"
    # scheme: "srm,gsiftp,root,http,https"
    # transfertool: "fts3"
    # cache_time: ""
    # user_deterministic_id: ""
    # poll_timeout: ""
    # submit_timeout: ""
    # bring_online: ""
    # queue_mode: ""
    # using_memcache: ""
    # ftsmonhosts: ""
