# Default values for rucio.
# This is a YAML-formatted file.
# Declare configuration parameters that are to be used when generating 
# OKD deployment YAML configs via Helm templates.

experiment: Uses $EXPERIMENT

# Number of pods to run for each daemon
abacusAccountCount: 1
abacusRseCount: 1

conveyorTransferSubmitterCount: 1
conveyorPollerCount: 1
conveyorFinisherCount: 1
conveyorStagerCount: 1
conveyorReceiverCount: 0

hermesCount: 1
judgeCleanerCount: 1
judgeEvaluatorCount: 1
judgeInjectorCount: 1
judgeRepairerCount: 1
undertakerCount: 1
reaperCount: 1 
transmogrifierCount: 1
minosCount: 1
necromancerCount: 1
replicaRecovererCount: 1

automatixCount: 1

# Service Account
serviceAccountName: useroot

# Daemon Image
image:
  repository: imageregistry.fnal.gov/rucio-ams/rucio-ams-daemons
  tag: latest
  pullPolicy: Always

# Pod Upgrade Strategy
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

minReadySeconds: 5

# Daemons Specific Configuration Parameters
abacusAccount:
  threads: 1

abacusRse:
  threads: 1

conveyorTransferSubmitter:
  threads: 1
  activities: "'User Subscriptions' 'Recovery'"
  sleepTime: 10
  resources:
    limits:
      memory: "600Mi"
      cpu: "700m"
    requests:
      memory: "200Mi"
      cpu: "700m"

conveyorPoller:
  threads: 1
  activities: "'User Subscriptions' 'Recovery'"
  resources:
    limits:
      memory: "600Mi"
      cpu: "700m"
    requests:
      memory: "200Mi"
      cpu: "700m"

conveyorFinisher:
  threads: 1
  activities: "'User Subscriptions' 'Recovery'"
  resources:
    limits:
      memory: "600Mi"
      cpu: "700m"
    requests:
      memory: "200Mi"
      cpu: "700m"

conveyorStager:
  threads: 1
  activities: "'User Subscriptions' 'Recovery'"
  resources:
    limits:
      memory: "600Mi"
      cpu: "700m"
    requests:
      memory: "200Mi"
      cpu: "700m"

judgeCleaner:
  threads: 1
  resources:
    limits:
      memory: "600Mi"
      cpu: "700m"
    requests:
      memory: "200Mi"
      cpu: "700m"

judgeEvaluator:
  threads: 1
  resources:
    limits:
      memory: "600Mi"
      cpu: "700m"
    requests:
      memory: "200Mi"
      cpu: "700m"

judgeInjector:
  threads: 1
  resources:
    limits:
      memory: "600Mi"
      cpu: "700m"
    requests:
      memory: "200Mi"
      cpu: "700m"

judgeRepairer:
  threads: 1
  resources:
    limits:
      memory: "600Mi"
      cpu: "700m"
    requests:
      memory: "200Mi"
      cpu: "700m"

undertaker:
  threads: 1
  resources:
    limits:
      memory: "600Mi"
      cpu: "700m"
    requests:
      memory: "200Mi"
      cpu: "700m"

reaper:
  scheme: "gsiftp"
  threads: 1
  resources:
    limits:
      memory: "600Mi"
      cpu: "700m"
    requests:
      memory: "200Mi"
      cpu: "700m"

replicaRecoverer:
  resources:
    limits:
      memory: "600Mi"
      cpu: "700m"
    requests:
      memory: "200Mi"
      cpu: "700m"

minos:
  threads: 1

necromancer:
  threads: 1

hermes:
  threads: 2
  useSSL: "True"
  bulk: "100"
  sleepTime: "10"

ftsRenewal:
  enabled: 1
  image:
    repository: imageregistry.fnal.gov/rucio-ams/rucio-ams-fts-cron
    pullPolicy: Always
  vo: "fermilab"
  #voms: "fermilab:/fermilab/Role=Production"
  voms: "fermilab:/fermilab"
  servers: "https://fts3-public.fnal.gov:8446"

automatix:
  resources:
    limits:
      memory: "600Mi"
      cpu: "700m"
    requests:
      memory: "200Mi"
      cpu: "700m"
  inputFile: "/opt/rucio/etc/automatix.json"
  sleepTime: "300"

# Config values used to configure the Rucio daemons
# These are turned into RUCIO_CFG_<section>_<variable>=value environment variables
config:
#  common:
  client:
    account: "automatix"
    auth_type: "x509_proxy"
    rucio_host: "https://int-rucio.fnal.gov"
    auth_host: "https://auth-int-rucio.fnal.gov"
    ca_cert: "/etc/grid-security/certificates"
    request_retries: 3
    protocol_stat_retries: 6
    client_x509_proxy: "/opt/proxy/x509up"

  automatix:
    rses: "DCACHE_BJWHITE_END, DCACHE_BJWHITE_END2"
    account: "automatix"
    sleep_time: 300
    set_metadata: "False"
    dataset_lifetime: 30
    scope: "automatix"

  messaging-cache:
    port: "11211"
    #ssl_key_file: ?
    #ssl_cert_file: ?
    destination: "/topic/rucio.events.int"
    brokers: "rucio-cache"
    voname: "fermilab"
    account: "memcache"


  messaging-hermes:
    brokers: "rucio-messenger"
    port: "443"
    username: "guest"
    password: "guest"
    port: "443"
    use_ssl: "True"
    ssl_key_file: "/opt/rucio/keys/new_userkey.pem"
    ssl_cert_file: "/opt/rucio/certs/usercert.pem"
    destination: "/topic/rucio.events.int"
    brokers: "rucio-messenger"
    broker_virtual_host: "/"
    voname: "/"
    email_from: "int Rucio <bjwhite@fnal.gov>"
    email_test: "bjwhite@fnal.gov"

  conveyor:
    max_time_in_queue: "User Subscriptions:5"
    ftshosts: "https://fts3-public.fnal.gov:8446"
    cacert: "/opt/certs/ca.pem"
    usercert: "/opt/proxy/x509up"

  monitor:
    carbon_server: "rucio-statsd"
    carbon_port: "8125"
    user_scope: "rucio_int_okd"
    enable_metrics: "True"

  policy:
    package: fermilab.generic
    support: "Brandon White <bjwhite@fnal.gov>"

optional_config:
  policy_pkg_dir: /opt/rucio/permissions
  #rucio_enable_logs: "True"
  #rucio_daemon_log_dir: /var/log/rucio
  #rucio_cfg_database_echo: 1

additionalSecrets:
  suspicious-replica-recoverer-input:
    secretName: suspicious-replica-recoverer-input
    mountPath: /opt/rucio/etc/suspicious_replica_recoverer.json
    subPath: suspicious_replica_recoverer.json
  automatix-input:
    secretName: automatix-input
    mountPath: /opt/rucio/etc/automatix.json
    subPath: automatix.json
