apiVersion: v1
description: Fermilab Helm chart for automatic testing of transfers of n files to m RSEs
home: https://github.com/bjwhite-fnal/rucio-ams
maintainers:
- email: bjwhite@fnal.gov 
  name: Brandon White 
name: rucio-autotransfer 
version: 1.0 
appVersion: 1.0 
