# Default values for rucio.
# This is a YAML-formatted file.
# Declare configuration parameters that are to be used when generating 
# OKD deployment YAML configs via Helm templates.

experiment: Uses $EXPERIMENT

# Number of pods to run for each daemon
reaperCount: 1
hermesCount: 1 

abacusAccountCount: 1
abacusCollectionReplicaCount: 1
abacusRseCount: 1

conveyorTransferSubmitterCount: 1
conveyorPollerCount: 1
conveyorFinisherCount: 1
conveyorStagerCount: 1
conveyorReceiverCount: 0

judgeCleanerCount: 1 
judgeEvaluatorCount: 1 
judgeInjectorCount: 1 
judgeRepairerCount: 1 

undertakerCount: 1
transmogrifierCount: 1
minosCount: 1 
necromancerCount: 1 
#kronosCount: 0
#cacheConsumerCount: 0
#auditor?

# Service Account
serviceAccountName: useroot

# Daemon Image
image:
  repository: imageregistry.fnal.gov/rucio-ams/rucio-ams-daemons
  tag: latest
  pullPolicy: Always

# Pod Upgrade Strategy
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

minReadySeconds: 5

# Daemons Specific Configuration Parameters
abacusAccount:
  threads: 1
  resources:
    limits:
      memory: "200Mi"
      cpu: "200m"
    requests:
      memory: "100Mi"
      cpu: "100m"

abacusRse:
  threads: 1
  resources:
    limits:
      memory: "200Mi"
      cpu: "200m"
    requests:
      memory: "100Mi"
      cpu: "100m"

abacusCollectionReplica:
  threads: 1
  resources:
    limits:
      memory: "200Mi"
      cpu: "200m"
    requests:
      memory: "100Mi"
      cpu: "100m"

conveyorTransferSubmitter:
  threads: 1
  activities: "'User Subscriptions' 'Recovery' 'Data Challenge'"
  sleepTime: 10
  resources:
    limits:
      memory: "200Mi"
      cpu: "200m"
    requests:
      memory: "100Mi"
      cpu: "100m"

conveyorPoller:
  threads: 1
  activities: "'User Subscriptions' 'Recovery' 'Data Challenge'"
  resources:
    limits:
      memory: "200Mi"
      cpu: "200m"
    requests:
      memory: "100Mi"
      cpu: "100m"

conveyorFinisher:
  threads: 1
  activities: "'User Subscriptions' 'Recovery' 'Data Challenge'"
  resources:
    limits:
      memory: "200Mi"
      cpu: "200m"
    requests:
      memory: "100Mi"
      cpu: "100m"

conveyorStager:
  threads: 1
  activities: "'User Subscriptions' 'Recovery' 'Data Challenge'"
  resources:
    limits:
      memory: "200Mi"
      cpu: "200m"
    requests:
      memory: "100Mi"
      cpu: "100m"

conveyorReceiver:
  threads: 1
  activities: "'User Subscriptions' 'Recovery' 'Data Challenge'"

judgeCleaner:
  threads: 1
  resources:
    limits:
      memory: "200Mi"
      cpu: "200m"
    requests:
      memory: "100Mi"
      cpu: "100m"

judgeEvaluator:
  threads: 1
  resources:
    limits:
      memory: "200Mi"
      cpu: "200m"
    requests:
      memory: "100Mi"
      cpu: "100m"

judgeInjector:
  threads: 1
  resources:
    limits:
      memory: "200Mi"
      cpu: "200m"
    requests:
      memory: "100Mi"
      cpu: "100m"

judgeRepairer:
  threads: 1
  resources:
    limits:
      memory: "200Mi"
      cpu: "200m"
    requests:
      memory: "100Mi"
      cpu: "100m"

transmogrifier:
  threads: 1
  resources:
    limits:
      memory: "200Mi"
      cpu: "200m"
    requests:
      memory: "100Mi"
      cpu: "100m"

undertaker:
  threads: 1

reaper:
  threads: 1
  resources:
    limits:
      memory: "200Mi"
      cpu: "200m"
    requests:
      memory: "100Mi"
      cpu: "100m"

minos:
  threads: 1

necromancer:
  threads: 1

hermes:
  threads: 2
  useSSL: "True"
  bulk: "100"
  sleepTime: "10"
  resources:
    limits:
      memory: "200Mi"
      cpu: "200m"
    requests:
      memory: "100Mi"
      cpu: "100m"

ftsRenewal:
  enabled: 1
  image:
    repository: imageregistry.fnal.gov/rucio-ams/rucio-ams-fts-cron
    pullPolicy: Always
  vo: "hypot"
  voms: "fermilab:/fermilab/hypot/Role=Production"
  servers: "https://fts3-public.fnal.gov:8446"

# Config values used to configure the Rucio daemons
# These are turned into RUCIO_CFG_<section>_<variable>=value environment variables
config:
  #common:
  core:
    use_temp_tables: "True"

  conveyor:
    max_time_in_queue: "User Subscriptions:5"
    ftshosts: "https://fts3-public.fnal.gov:8446"
    cacert: "/opt/certs/ca.pem"
    usercert: "/opt/proxy/x509up"
    bring_online: "259200"

  transfers:
    srm_https_compatibility: True

  monitor:
    carbon_server: "rucio-statsd"
    carbon_port: "8125"
    user_scope: "rucio_hypot_okd"
    enable_metrics: "True"

  messaging-cache:
    port: "11211"
    destination: "/topic/rucio.events.hypot"
    brokers: "rucio-cache"
    voname: "hypot"
    account: "memcache"

  messaging-hermes:
    brokers: "rucio-messenger"
    port: "443"
    username: "guest"
    password: "guest"
    use_ssl: "True"
    ssl_key_file: "/opt/rucio/keys/new_userkey.pem"
    ssl_cert_file: "/opt/rucio/certs/usercert.pem"
    destination: "/topic/rucio.events.hypot"
    broker_virtual_host: "/"
    voname: "/"
    email_from: "HYPOT Rucio <bjwhite@fnal.gov>"
    email_test: "bjwhite@fnal.gov"

optional_config:
  policy_pkg_dir: /opt/rucio/permissions
  #rucio_cfg_database_echo: 1
  delegate_fts_proxy: "true"
