# Rucio Web UI container configuration options
# This is a YAML-formatted file
# Declare variables to be passed into your templates.

serviceAccountName: useroot

rucio_ca_path: /etc/grid-security/certificates

image:
  repository: imageregistry.fnal.gov/rucio-ams/rucio-ams-webui
  tag: latest
  pullPolicy: Always

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

minReadySeconds: 5

exposeErrorLogs: 0

ingress:
  enabled: 0

webuiRoute:
  app: rucio-webui
  host: webui-rubin-rucio.slac.stanford.edu
  serviceName: rucio-rubin-webui

service:
  type: ClusterIP
  port: 443 
  targetPort: 443
  tls:
    enabled: true

monitor:
  carbon_server: "rucio-statsd"
  carbon_port: "8125"
  user_scope: "rucio_rubin"
  enable_metrics: "True"

logging:
  log_level: 0

httpd_config:
  log_dir: "/rucio/logs"

config:
  policy:
    package: rubin
    support: "Brandon White <bjwhite@fnal.gov>"

optional_config:
  experiment: Uses $EXPERIMENT 
  policy_pkg_dir: /opt/rucio/permissions
  rucio_enable_logfile: "True"
