apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "rucio.fullname" . }}
  labels:
    app: {{ template "rucio.name" . }}
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: {{ template "rucio.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.strategy.type }}
{{- if eq .Values.strategy.type "RollingUpdate" }}
    {{- with .Values.strategy.rollingUpdate }}
    rollingUpdate:
{{ toYaml . | trim | indent 6 }}
    {{- end }}
{{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ template "rucio.name" . }}
        release: {{ .Release.Name }}
    spec:
    {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
    {{- end }} 
      volumes:
        - name: host-cert
          secret:
            secretName: host-cert
        - name: host-key
          secret:
            secretName: host-key
        - name: ca-bundle
          secret:
            secretName: ca-bundle
        - name: osg-authentication-volume
          persistentVolumeClaim:
            claimName: pvc-osg-authentication 
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: host-cert
              mountPath: /etc/grid-security/hostcert.pem
              subPath: hostcert.pem
              readOnly: true
            - name: host-key
              mountPath: /etc/grid-security/hostkey.pem
              subPath: hostkey.pem
              readOnly: true
            - name: ca-bundle
              mountPath: /etc/grid-security/ca.pem
              subPath: ca.pem
              readOnly: true
            - name: osg-authentication-volume
              mountPath: /etc/grid-security/certificates
          env:
            - name: EXPERIMENT
              value: "{{ .Values.experiment }}"
