apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "rucio.fullname" . }}
  labels:
    app: {{ template "rucio.name" . }}
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: {{ template "rucio.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.strategy.type }}
{{- if eq .Values.strategy.type "RollingUpdate" }}
    {{- with .Values.strategy.rollingUpdate }}
    rollingUpdate:
{{ toYaml . | trim | indent 6 }}
    {{- end }}
{{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ template "rucio.name" . }}
        release: {{ .Release.Name }}
    spec:
    {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
    {{- end }} 
      volumes:
        - name: host-cert-key-combined
          secret:
            secretName: host-cert-key-combined
        - name: host-cert
          secret:
            secretName: host-cert
        - name: host-key
          secret:
            secretName: host-key
        - name: ca-bundle
          secret:
            secretName: ca-bundle
        - name: osg-authentication-volume
          persistentVolumeClaim:
            claimName: pvc-osg-authentication 
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: host-cert-key-combined
              mountPath: /etc/grid-security/hostcertkeycombined.pem
              subPath: hostcertkeycombined.pem
              readOnly: true
            - name: host-cert
              mountPath: /etc/grid-security/hostcert.pem
              subPath: hostcert.pem
              readOnly: true
            - name: host-key
              mountPath: /etc/grid-security/hostkey.pem
              subPath: hostkey.pem
              readOnly: true
            - name: ca-bundle
              mountPath: /etc/grid-security/ca.pem
              subPath: ca.pem
              readOnly: true
            - name: osg-authentication-volume
              mountPath: /etc/grid-security/certificates
          env:
            {{- range $key1, $val1 := .Values.config }}
            {{- range $key2, $val2 := $val1}}
            - name: RUCIO_CFG_{{ $key1 | upper }}_{{ $key2 | upper }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "rucio.fullname" $ }}.cfg
                  key: {{ $key1 }}_{{ $key2 }}
            {{- end}}
            {{- end}}
            - name: EXPERIMENT
              value: "{{ .Values.experiment }}"
            - name: RUCIO_LOG_FORMAT
              value: '[%{%Y-%m-%d %H:%M:%S}t]\t%v\t%h\t%{X-Forwarded-For}i\t%{X-Rucio-RequestId}i\t%>s\t%I\t%B\t%D\t\"%r\"\t\"%{X-Rucio-Auth-Token}i\"\t\"%{User-Agent}i\"\t%{X-Rucio-Script}i'
            - name: RUCIO_CFG_MONITOR_CARBON_SERVER
              value: "{{ .Values.monitor.carbon_server }}"
            - name: RUCIO_CFG_MONITOR_CARBON_PORT
              value: "{{ .Values.monitor.carbon_port }}"
            - name: RUCIO_CFG_MONITOR_USER_SCOPE
              value: "{{ .Values.monitor.user_scope }}"
            - name: RUCIO_CFG_DATABASE_ECHO
              value: "{{ .Values.logging.log_level }}"
            - name: RUCIO_CFG_WEBUI_USERCERT
              value: "{{ .Values.webui_certkeycombined_path }}"
            - name: RUCIO_CA_PATH
              value: "{{ .Values.rucio_ca_path }}"
