# Default values for rucio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Number of pods to run for server (replicaCount) and auth server (authReplicaCount)
replicaCount: 1 
authReplicaCount: 1
traceReplicaCount: 0

# Leave this as useroot (or whatever the ServiceAccount setup by the admins with the ability to run privileged containers).
serviceAccountName: useroot

experiment: Uses $EXPERIMENT

image:
  repository: imageregistry.fnal.gov/rucio-ams/rucio-ams-server
  pullPolicy: Always

serverResources:
  limits:
    memory: "600Mi"
    cpu: "700m"
  requests:
    memory: "200Mi"
    cpu: "200m"

authServerResources:
  limits:
    memory: "600Mi"
    cpu: "700m"
  requests:
    memory: "200Mi"
    cpu: "200m"

serverType:
  server: flask
  authServer: flask
  traceServer: trace

serverRoute:
  app: rucio-mu2e-rucio-server
  host: mu2e-rucio.fnal.gov
  serviceName: rucio-server

authServerRoute:
  app: rucio-mu2e-rucio-server-auth
  host: auth-mu2e-rucio.fnal.gov
  serviceName: rucio-server-auth

useSSL:
  authServer: 1
  server: 1

service:
  type: ClusterIP
  port: 443
  targetPort: 443

authService:
  type: ClusterIP
  port: 443
  targetPort: 443
  tls:
    enabled: true

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

minReadySeconds:
  server: 5
  authServer: 5

exposeErrorLogs:
  server: 1
  authServer: 1

httpd_config:
  mpm_mode: "prefork"
  use_ca_path: "1"
  start_servers: "8"
  min_spare_servers: "5"
  max_spare_servers: "20"
  server_limit: "256"
  max_clients: "256"
  max_requests_per_child: "4000"
  enable_status: "False"

livenessProbe:
  server:
    initialDelaySeconds: 10
    periodSeconds: 60
    timeoutSeconds: 30
  authServer:
    initialDelaySeconds: 10
    periodSeconds: 60
    timeoutSeconds: 30

config: 
  # common:
  core:
    use_temp_tables: "True"

  monitor:
    carbon_server: "rucio-statsd"
    carbon_port: "8125"
    user_scope: "rucio_mu2e_okd"
    enable_metrics: "False"

  # Configure the policy package that is to be used for this deployment.
  policy:
    package: fermilab.generic
    support: "Brandon White <bjwhite@fnal.gov>"

  # Set up request routing to the auth server
  api:
    endpoints: auth,accountlimits,accounts,config,credentials,dids,export,heartbeats,identities,import,lifetime_exceptions,locks,meta,ping,redirect,replicas,requests,rses,rules,scopes,subscriptions
    

# FNAL (and likely OKD) Specific Configuration Stuff
optional_config:
  # Set the path (inside the container) where the experiment policy package will be located.
  policy_pkg_dir: /opt/rucio/permissions
  rucio_metrics_port: 8080

  # Database debugging messages
  #rucio_cfg_database_echo: 1

authIngress:
  enabled: false

ingress:
  enabled: false

monitoring:
  enabled: false

metricsExporterResources: {}
errorLogsExporterResources: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
