# Rucio Web UI container configuration options
# This is a YAML-formatted file
# Declare variables to be passed into your templates.

serviceAccountName: useroot

rucio_ca_path: /etc/grid-security/certificates
webui_certkeycombined_path: /etc/grid-security/hostcertkeycombined.pem

image:
  repository: imageregistry.fnal.gov/rucio-ams/rucio-ams-webui
  tag: latest
  pullPolicy: Always

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

minReadySeconds: 5

proxy:
  rucioProxy: "hypot-rucio.fnal.gov"
  rucioAuthProxy: "auth-hypot-rucio.fnal.gov"


exposeErrorLogs: 0

ingress:
  enabled: 0

webuiRoute:
  app: rucio-webui
  host: webui-hypot-rucio.fnal.gov
  serviceName: rucio-hypot-rucio-ui

service:
  type: ClusterIP
  port: 443 
  targetPort: 443
  tls:
    enabled: true

monitor:
  carbon_server: "rucio-statsd"
  carbon_port: "8125"
  user_scope: "rucio_hypot_okd"
  enable_metrics: "True"

logging:
  log_level: 0

httpd_config:
  log_dir: "/rucio/logs"

config:
  core:
    use_temp_tables: "True"

optional_config:
  experiment: Uses $EXPERIMENT 
  policy_pkg_dir: /opt/rucio/permissions
