# Default values for rucio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Number of pods to run for server (replicaCount) and auth server (authReplicaCount)
replicaCount: 1 
authReplicaCount: 1
traceReplicaCount: 0

# Leave this as useroot (or whatever the ServiceAccount setup by the admins with the ability to run privileged containers).
serviceAccountName: useroot

experiment: Uses $EXPERIMENT

image:
  repository: imageregistry.fnal.gov/rucio-fnal/fnal-rucio-server
  pullPolicy: Always

serverResources:
  limits:
    memory: "600Mi"
    cpu: "700m"
  requests:
    memory: "200Mi"
    cpu: "200m"

authServerResources:
  limits:
    memory: "600Mi"
    cpu: "700m"
  requests:
    memory: "200Mi"
    cpu: "200m"

serverType:
    server: flask
    authServer: flask
    traceserver: trace

serverRoute:
  app: rucio-icarus-rucio-server
  host: icarus-rucio.okd.fnal.gov
  serviceName: rucio-server

authServerRoute:
  app: rucio-icarus-rucio-server-auth
  host: auth-icarus-rucio.okd.fnal.gov
  serviceName: rucio-server-auth

useSSL:
  authServer: 1
  server: 1

service:
  type: ClusterIP
  port: 443
  targetPort: 443

authService:
  type: ClusterIP
  port: 443
  targetPort: 443
  tls:
    enabled: true

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

minReadySeconds:
  server: 5
  authServer: 5

# Don't worry about this, we have our own logging solution. This is for CERN.
exposeErrorLogs:
  server: 0
  authServer: 0

httpd_config:
  mpm_mode: "prefork"
  use_ca_path: "1"
  start_servers: "1"
  min_spare_servers: "1"
  max_spare_servers: "1"
  server_limit: "1"
  max_clients: "10"
  max_requests_per_child: "200"

persistentVolumes:
  rucio-logs:
    name: "pv-rucio-icarus-logs"
    mountPath: /rucio/logs

config: 
  common:
    logdir: /rucio/logs

  monitor:
    carbon_server: "lsdataitb.fnal.gov"
    carbon_port: "8225"
    user_scope: "rucio_icarus_okd"
    enable_metrics: "true"

  policy:
    package: fermilab
    support: "Brandon White <bjwhite@fnal.gov>"

  api:
    endpoints: auth,accountlimits,accounts,config,credentials,dids,export,heartbeats,identities,import,lifetime_exceptions,locks,meta,ping,redirect,replicas,requests,rses,rules,scopes,subscriptions

optional_config:
  policy_pkg_dir: /opt/rucio/permissions
  rucio_enable_logfile: "True"
  rucio_httpd_log_dir: /rucio/logs
  #rucio_cfg_database_echo: 1

authIngress:
  enabled: false

ingress:
  enabled: false

monitoring:
  enabled: false

metricsExporterResources: {}
errorLogsExporterResources: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
