# Default values for rucio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Number of pods to run for server (replicaCount) and auth server (authReplicaCount)
replicaCount: 1 
authReplicaCount: 1

serviceAccountName: useroot

experiment: Uses $EXPERIMENT

image:
  repository: bjwhitefnal/fnal-rucio-server
  tag: latest
  pullPolicy: Always

serverRoute:
  app: rucio-icarus-rucio-server
  host: icarus-rucio.okd.fnal.gov
  serviceName: rucio-server

useSSL:
  authServer: 1
  server: 1

authServerRoute:
  app: rucio-icarus-rucio-server-auth
  host: auth-icarus-rucio.okd.fnal.gov
  serviceName: rucio-server-auth

service:
  type: ClusterIP
  port: 443
  targetPort: 443

authService:
  type: ClusterIP
  port: 443
  targetPort: 443
  tls:
    enabled: true

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

minReadySeconds: 5

exposeErrorLogs:
  server: 0
  authServer: 0

httpd_config:
  mpm_mode: "prefork"
  use_ca_path: "1"
  start_servers: "1"
  min_spare_servers: "1"
  max_spare_servers: "1"
  server_limit: "1"
  max_clients: "10"
  max_requests_per_child: "200"

config: 
  monitor:
    carbon_server: "lsdataitb.fnal.gov"
    carbon_port: "8225"
    user_scope: "rucio.icarus_okd"

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

optional_config:
  #rucio_cfg_database_echo: 1
  delegate_fts_proxy: "true"
  rucio_fts_voms: "fermilab:/fermilab/Role=Production"
