{{- if .Values.esCron.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-run-escron
spec:
  schedule: "{{ .Values.esCron.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Release.Name }}-rucio-edit
          volumes:
          - name: usercert
            secret:
              secretName: {{ .Release.Name }}-escron-cert
          - name: userkey
            secret:
              secretName: {{ .Release.Name }}-escron-key
{{- range $key, $val := .Values.persistentVolumes }}
          - name: {{ $key }}
            persistentVolumeClaim:
              claimName: {{ $val.name }}
{{- end}}
          containers:
            - name: run-escron
              image: "{{ .Values.esCron.image.repository }}:{{ .Values.esCron.image.tag }}"
              imagePullPolicy: {{ .Values.esCron.image.pullPolicy }}
              volumeMounts:
                - name: usercert
                  mountPath: /opt/rucio/hostcert.pem
                - name: userkey
                  mountPath: /opt/rucio/hostkey.pem
{{- range $key, $val := .Values.persistentVolumes }}
                - name: {{ $key }}
                  mountPath: {{ $val.mountPath }}
{{- end}}
              env:
                {{- range $key1, $val1 := .Values.optional_config }}
                - name: {{ $key1 | upper }}
                  value: "{{ $val1  }}"
                {{- end}}
                - name: RUCIO_BROKER_HOST
                  value: {{ .Values.config.env.rucio_broker_host }}
                - name: RUCIO_BROKER_PORT
                  value: {{ .Values.config.env.rucio_broker_port }}
                - name: RUCIO_BROKER_QUEUE
                  value: {{ .Values.config.env.rucio_broker_queue }}
                - name: RUCIO_BROKER_SUBSCRIPTION_ID
                  value: {{ .Values.config.env.rucio_broker_subscription_id }}
                - name: CONSUMER_HOST
                  value: {{ .Values.config.env.consumer_host }}
                - name: CONSUMER_PORT
                  value: {{ .Values.config.env.consumer_port }}
          restartPolicy: OnFailure
{{ end }}
