{{- if gt .Values.filebeatCount 0.0 -}}
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "pv-rucio-{{ .Values.experiment }}-logs"
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "1Gi"
{{ end }}
