apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rucio
resources:
  - rucio-daemons-helm.yaml
configMapGenerator:
  - name: rucio-ams-daemons
    files:
      - values.yaml=rucio-ams-daemons.yaml
configurations:
  - kustomizeconfig.yaml
