{{- $fullName := include "rucio.fullname" . -}}
{{- $targetPort := .Values.authService.port -}}
{{- if .Values.openShift.enabled }}
{{- with .Values.openShift.authServer }}
apiVersion: v1
kind: Route
metadata:
  name: {{ $fullName }}-auth-route
spec:
  host: {{ .host }}
  path: /auth
  port:
    targetPort: {{ $targetPort }}
  to:
    kind: Service
    name: {{ $fullName }}-auth
  {{- if .tls.enabled }}
  tls:
    termination: edge            
    key: {{ toYaml .tls.key | indent 8 }}
    certificate: {{ toYaml .tls.certificate | indent 8 }}
  {{- end }}
{{- end }}
{{- end }}


