---
# Source: rucio-messenger/templates/messenger_service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fnal-rucio-messenger
  labels:
    app: rucio-messenger
    release: fnal
spec:
  type: ClusterIP 
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    - port: 61613
      targetPort: 61613
      protocol: TCP
      name: http
  selector:
    app: rucio-messenger
    release: fnal
---
# Source: rucio-messenger/templates/messenger_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fnal-rucio-messenger
  labels:
    app: rucio-messenger
    release: fnal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rucio-messenger
      release: fnal
  minReadySeconds: 
  template:
    metadata:
      labels:
        app: rucio-messenger
        release: fnal
    spec:
      serviceAccountName: useroot
      volumes:
        - name: ssl-credentials
          secret:
            secretName: ssl-secrets
        - name: rabbitmq-conf
          secret:
            secretName: fnal-rabbitmq-conf
        - name: enabled-plugins
          secret: 
            secretName: fnal-rabbitmq-enabled-plugins
      containers:
        - name: rucio-messenger
          image: "imageregistry.fnal.gov/docker.io/rabbitmq:3"
          imagePullPolicy: Always
          command: ["rabbitmq-server"]
          ports:
            - containerPort: 443
            - containerPort: 61613
          volumeMounts:
            - name: ssl-credentials
              mountPath: /etc/rabbitmq/ssl
              readOnly: true
            - name: rabbitmq-conf
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
            - name: enabled-plugins
              mountPath: /etc/rabbitmq/enabled_plugins
              subPath: enabled_plugins
          env:
            - name: EXPERIMENT
              value: "dune"
