apiVersion: apps/v1
kind: Deployment
metadata:
  name: fnal-rucio-webui
spec:
  template:
    spec:
      serviceAccountName: useroot
      volumes:
        - name: nextjs-config
          configMap:
            name: webui-patch
        - name: rucio-conf-j2
          configMap:
            name: webui-rucio-conf-j2
      containers:
        - name: rucio-webui 
          volumeMounts:
            - name: nextjs-config
              mountPath: /opt/rucio/webui/next.config.js
              subPath: next.config.js
            - name: rucio-conf-j2
              mountPath: /tmp/rucio.conf.j2
              subPath: rucio.conf.j2