{{- if gt .Values.conveyorFinisherCount 0.0 -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-conveyor-finisher
  labels:
    app: {{ template "rucio.name" . }}
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.conveyorFinisherCount }}
  selector:
    matchLabels:
      app: {{ template "rucio.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.strategy.type }}
{{- if eq .Values.strategy.type "RollingUpdate" }}
    {{- with .Values.strategy.rollingUpdate }}
    rollingUpdate:
{{ toYaml . | trim | indent 6 }}
    {{- end }}
{{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ template "rucio.name" . }}
        release: {{ .Release.Name }}
    spec:
    {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
    {{- end }}
      volumes:
      - name: host-cert
        secret:
          secretName: host-cert
      - name: host-key
        secret:
          secretName: host-key
      - name: ca-bundle 
        secret:
          secretName: ca-bundle 
      - name: osg-authentication-volume
        persistentVolumeClaim:
          claimName: pvc-osg-authentication
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: host-cert
              mountPath: /etc/grid-security/hostcert.pem
              subPath: hostcert.pem
              readOnly: true
            - name: host-key
              mountPath: /etc/grid-security/hostkey.pem
              subPath: hostkey.pem
              readOnly: true
            - name: ca-bundle 
              mountPath: /etc/grid-security/ca.pem
              subPath: ca.pem
              readOnly: true
            - name: osg-authentication-volume
              mountPath: /etc/grid-security/certificates
          env:
            {{- range $key1, $val1 := .Values.config }}
            {{- range $key2, $val2 := $val1}}
            - name: RUCIO_CFG_{{ $key1 | upper }}_{{ $key2 | upper }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "rucio.fullname" $ }}.cfg
                  key: {{ $key1 }}_{{ $key2 }}
            {{- end}}
            {{- end}}
            - name: EXPERIMENT
              value: "{{ .Values.experiment }}"
            - name: RUCIO_DAEMON
              value: "conveyor-finisher"
            - name: RUCIO_DAEMON_ARGS
              value: "--total-threads {{ .Values.conveyorFinisher.threads }} --activities {{ .Values.conveyorFinisher.activities }}"
            - name: DELEGATE_FTS_PROXY
              value: "true"
            - name: RUCIO_CFG_MONITOR_CARBON_SERVER
              value: "{{ .Values.monitor.carbon_server }}"
            - name: RUCIO_CFG_MONITOR_CARBON_PORT
              value: "{{ .Values.monitor.carbon_port }}"
            - name: RUCIO_CFG_MONITOR_USER_SCOPE
              value: "{{ .Values.monitor.user_scope }}"
            - name: RUCIO_CFG_DATABASE_ECHO
              value: "{{ .Values.logging.log_level }}"
            - name: FNAL_EXP_RUCIO_VOMS_STR
              value: "{{ .Values.ftsRenewal.voms }}"
{{ end }}
