{{- if gt .Values.hermesCount 0.0 -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-hermes
  labels:
    app: {{ template "rucio.name" . }}
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.hermesCount }}
  selector:
    matchLabels:
      app: {{ template "rucio.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.strategy.type }}
{{- if eq .Values.strategy.type "RollingUpdate" }}
    {{- with .Values.strategy.rollingUpdate }}
    rollingUpdate:
{{ toYaml . | trim | indent 6 }}
    {{- end }}
{{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ template "rucio.name" . }}
        release: {{ .Release.Name }}
    spec:
    {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
    {{- end }}
      volumes:
      - name: ssl-credentials 
      secret:
          secretName: ssl-secrets 
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: ssl-credentials 
              mountPath: /etc/grid-security/hostcert.pem
          env:
            {{- range $key1, $val1 := .Values.config }}
            {{- range $key2, $val2 := $val1}}
            - name: RUCIO_CFG_{{ $key1 | upper }}_{{ $key2 | upper }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "rucio.fullname" $ }}.cfg
                  key: {{ $key1 }}_{{ $key2 }}
            {{- end}}
            {{- end}}
            - name: EXPERIMENT
              value: "{{ .Values.experiment }}"
            - name: RUCIO_DAEMON
              value: "hermes"
            - name: RUCIO_DAEMON_ARGS
              value: "--threads {{ .Values.hermes.threads }} --bulk {{ .Values.hermes.bulk }} --delay {{ .Values.hermes.delay }}"
            - name: RUCIO_CFG_MONITOR_CARBON_SERVER
              value: "{{ .Values.monitor.carbon_server }}"
            - name: RUCIO_CFG_MONITOR_CARBON_PORT
              value: "{{ .Values.monitor.carbon_port }}"
            - name: RUCIO_CFG_MONITOR_USER_SCOPE
              value: "{{ .Values.monitor.user_scope }}"
            - name: RUCIO_CFG_DATABASE_ECHO
              value: "{{ .Values.logging.log_level }}"
            {{ if .Values.hermes.username }}
            - name: RUCIO_CFG_MESSAGING_HERMES_USERNAME
              value: "{{ .Values.hermes.username }}" 
            {{ end }}
            {{ if .Values.hermes.password }}
            - name: RUCIO_CFG_MESSAGING_HERMES_PASSWORD 
              value: "{{ .Values.hermes.password }}"
            {{ end }}
            {{ if .Values.hermes.port }}
            - name: RUCIO_CFG_MESSAGING_HERMES_PORT 
              value: "{{ .Values.hermes.port }}"
            {{ end }}
            {{ if .Values.hermes.nonssl_port }}
            - name: RUCIO_CFG_MESSAGING_HERMES_NONSSL_PORT 
              value: "{{ .Values.hermes.nonssl_port }}"
            {{ end }}
            {{ if .Values.hermes.use_ssl }}
            - name: RUCIO_CFG_MESSAGING_HERMES_USE_SSL 
              value: "{{ .Values.hermes.use_ssl }}"
            {{ end }}
            {{ if .Values.hermes.destination }}
            - name: RUCIO_CFG_MESSAGING_HERMES_DESTINATION 
              value: "{{ .Values.hermes.destination }}"  
            {{ end }}
            {{ if .Values.hermes.voname }}
            - name: RUCIO_CFG_MESSAGING_HERMES_VONAME 
              value: "{{ .Values.hermes.voname }}"
            {{ end }}
            {{ if .Values.hermes.email_from }}
            - name: RUCIO_CFG_MESSAGING_HERMES_EMAIL_FROM 
              value: "{{ .Values.hermes.email_from }}"  
            {{ end }}
            {{ if .Values.hermes.email_test }}
            - name: RUCIO_CFG_MESSAGING_HERMES_EMAIL_TEST
              value: "{{ .Values.hermes.email_test }}"  
            {{ end }}
{{ end }}
