{{- if gt .Values.hermesCount 0.0 -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-hermes
  labels:
    app: {{ template "rucio.name" . }}
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.hermesCount }}
  selector:
    matchLabels:
      app: {{ template "rucio.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.strategy.type }}
{{- if eq .Values.strategy.type "RollingUpdate" }}
    {{- with .Values.strategy.rollingUpdate }}
    rollingUpdate:
{{ toYaml . | trim | indent 6 }}
    {{- end }}
{{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ template "rucio.name" . }}
        release: {{ .Release.Name }}
    spec:
    {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
    {{- end }}
{{ if .Values.hermes.useSSL }}
      volumes:
        - name: usercert
          secret:
            secretName: host-cert
        - name: userkey
          secret:
            secretName: host-key
{{ end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{ if .Values.hermes.useSSL }}
          volumeMounts:
            - name: usercert
              mountPath: /opt/rucio/certs/
            - name: userkey
              mountPath: /opt/rucio/keys/
{{ end }}
          env:
            {{- range $key1, $val1 := .Values.config }}
            {{- range $key2, $val2 := $val1}}
            - name: RUCIO_CFG_{{ $key1 | upper }}_{{ $key2 | upper }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "rucio.fullname" $ }}.cfg
                  key: {{ $key1 }}_{{ $key2 }}
            {{- end}}
            {{- end}}
            - name: EXPERIMENT
              value: "{{ .Values.experiment }}"
            - name: RUCIO_DAEMON
              value: "hermes"
            - name: RUCIO_DAEMON_ARGS
              value: "--threads {{ .Values.hermes.threads }} --bulk {{ .Values.hermes.bulk }} --delay {{ .Values.hermes.delay }}"
            - name: RUCIO_CFG_MONITOR_CARBON_SERVER
              value: "{{ .Values.monitor.carbon_server }}"
            - name: RUCIO_CFG_MONITOR_CARBON_PORT
              value: "{{ .Values.monitor.carbon_port }}"
            - name: RUCIO_CFG_MONITOR_USER_SCOPE
              value: "{{ .Values.monitor.user_scope }}"
{{ end }}
