{{- if gt .Values.judgeEvaluatorCount 0.0 -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-judge-evaluator
  labels:
    app: {{ template "rucio.name" . }}
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.judgeEvaluatorCount }}
  selector:
    matchLabels:
      app: {{ template "rucio.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.strategy.type }}
{{- if eq .Values.strategy.type "RollingUpdate" }}
    {{- with .Values.strategy.rollingUpdate }}
    rollingUpdate:
{{ toYaml . | trim | indent 6 }}
    {{- end }}
{{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ template "rucio.name" . }}
        release: {{ .Release.Name }}
    spec:
    {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
    {{- end }}
      volumes:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          env:
            {{- range $key1, $val1 := .Values.config }}
            {{- range $key2, $val2 := $val1}}
            - name: RUCIO_CFG_{{ $key1 | upper }}_{{ $key2 | upper }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "rucio.fullname" $ }}.cfg
                  key: {{ $key1 }}_{{ $key2 }}
            {{- end}}
            {{- end}}
            - name: EXPERIMENT
              value: "{{ .Values.experiment }}"
            - name: RUCIO_DAEMON
              value: "judge-evaluator"
            - name: RUCIO_DAEMON_ARGS
              value: "--threads {{ .Values.judgeEvaluator.threads }}"
            - name: RUCIO_CFG_MONITOR_CARBON_SERVER
              value: "{{ .Values.monitor.carbon_server }}"
            - name: RUCIO_CFG_MONITOR_CARBON_PORT
              value: "{{ .Values.monitor.carbon_port }}"
            - name: RUCIO_CFG_MONITOR_USER_SCOPE
              value: "{{ .Values.monitor.user_scope }}"
            - name: RUCIO_CFG_DATABASE_ECHO
              value: "{{ .Values.logging.log_level }}"
            - name: FNAL_EXP_RUCIO_VOMS_STR
              value: "{{ .Values.ftsRenewal.voms }}"
{{ end }}
