---
serviceAccountName: useroot
logstashCount: 1
experiment: Uses $EXPERIMENT
minReadySeconds: 5

image:
  repository: imageregistry.fnal.gov/rucio-fnal/fnal-rucio-logstash
  tag: latest
  pullPolicy: Always

service:
  port: 5044
  targetPort: 5044

logstashRoute:
  app: rucio-logstash
  serviceName: logstash
